{
 "title": "Dashboard de prueba",
 "tags": [ "test" ],
 "time": { "from": "now-5m", "to": "now+1m" },
 "refresh": "auto",
 "panels": [
  {
   "title": "CPU0",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r.task == \"TOTAL_CPU0\")\n"
    }
   ]
  },
  {
   "title": "CPU1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r.task == \"TOTAL_CPU1\")\n"
    }
   ]
  },
  {
   "title": "CPU Pi Temp(Cº)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"cpu_temp\")\n"
    }
   ]
  },
  {
   "title": "RPI5 CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n      r._measurement == \"cpu\" and\r\n      r._field == \"usage_active\"\r\n  )\r\n  |> mean()\r\n"
    }
   ]
  },
  {
   "title": "Uso CPU0",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r.task == \"TOTAL_CPU0\")\n"
    }
   ]
  },
  {
   "title": "Uso CPU1",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r.task == \"TOTAL_CPU1\")\n"
    }
   ]
  },
  {
   "title": "Camara",
   "type": "text",
   "gridPos": { "h": 15, "w": 6, "x": 10, "y": 4 },
   "options": {
    "content": "<div style=\"width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:black;\"><img src=\"http://192.168.50.53:8080/stream\" style=\"max-width:100%;max-height:100%;object-fit:contain;\"/></div>"
   }
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"logs\")\n  |> keep(columns: [\"_time\", \"_value\", \"level\", \"robot\"])\n"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"logs\")\n  |> keep(columns: [\"_time\", \"_value\", \"level\", \"robot\"])\n"
    }
   ]
  },
  {
   "title": "ESP Uptime (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"uptime_sec\")\n"
    }
   ]
  },
  {
   "title": "ESP Uptime (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"system\")\n  |> filter(fn: (r) => r._field == \"uptime_sec\")\n"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "logs",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"logs\")\n  |> keep(columns: [\"_time\", \"_value\", \"level\", \"robot\"])\n"
    }
   ]
  },
  {
   "title": "Left Motor Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motor_cal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"target_l\" or r[\"_field\"] == \"actual_l\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Right Motor Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motor_cal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"target_r\" or r[\"_field\"] == \"actual_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery Voltaje",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power_system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_mv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Battery Voltaje",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power_system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage_mv\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Robot Current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current_ma\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Robot Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power_system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"power_mw\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "LAN Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\" or r[\"interface\"] == \"wlan0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\" or r[\"_field\"] == \"bytes_sent\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> map(fn: (r) => ({ r with _value: (r._value * 8.0) / 1000000.0 }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _field: r.interface + \"_\" + r._field }))\r\n  |> yield(name: \"velocidad_mbps\")"
    }
   ]
  },
  {
   "title": "Left Motor Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motor_cal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"v_final_l\" or r[\"_field\"] == \"v_ff_l\" or r[\"_field\"] == \"v_d_l\" or r[\"_field\"] == \"v_i_l\" or r[\"_field\"] == \"v_p_l\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Right Motor Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"motor_cal\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"v_final_r\" or r[\"_field\"] == \"v_ff_r\" or r[\"_field\"] == \"v_d_r\" or r[\"_field\"] == \"v_i_r\" or r[\"_field\"] == \"v_p_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Siguelineas Left",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"line_follower\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"actual_l\" or r[\"_field\"] == \"i_eff_l\" or r[\"_field\"] == \"d_eff_l\" or r[\"_field\"] == \"p_eff_l\" or r[\"_field\"] == \"target_l\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Siguelineas Right",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"line_follower\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"actual_r\" or r[\"_field\"] == \"i_eff_r\" or r[\"_field\"] == \"d_eff_r\" or r[\"_field\"] == \"p_eff_r\" or r[\"_field\"] == \"target_r\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Posicion Linea",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"line_sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"max0\" or r[\"_field\"] == \"max1\" or r[\"_field\"] == \"max2\" or r[\"_field\"] == \"max3\" or r[\"_field\"] == \"max4\" or r[\"_field\"] == \"max5\" or r[\"_field\"] == \"max6\" or r[\"_field\"] == \"max7\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lectura Raw",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"line_sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"raw0\" or r[\"_field\"] == \"raw1\" or r[\"_field\"] == \"raw2\" or r[\"_field\"] == \"raw3\" or r[\"_field\"] == \"raw4\" or r[\"_field\"] == \"raw5\" or r[\"_field\"] == \"raw6\" or r[\"_field\"] == \"raw7\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Posicion Linea",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"line_sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"s0\" or r[\"_field\"] == \"s1\" or r[\"_field\"] == \"s2\" or r[\"_field\"] == \"s3\" or r[\"_field\"] == \"s4\" or r[\"_field\"] == \"s5\" or r[\"_field\"] == \"s6\" or r[\"_field\"] == \"s7\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Posicion Linea",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"line_sensor\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min0\" or r[\"_field\"] == \"min1\" or r[\"_field\"] == \"min2\" or r[\"_field\"] == \"min3\" or r[\"_field\"] == \"min4\" or r[\"_field\"] == \"min5\" or r[\"_field\"] == \"min6\" or r[\"_field\"] == \"min7\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "uROS Latency (ms)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"esp_diagnostics\")\n  |> filter(fn: (r) => r._field == \"latency\")\n"
    }
   ]
  },
  {
   "title": "uROS Jitter (ms)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"esp_diagnostics\")\n  |> filter(fn: (r) => r._field == \"jitter\")\n"
    }
   ]
  },
  {
   "title": "uROS Offset (ms)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"esp_diagnostics\")\n  |> filter(fn: (r) => r._field == \"offset\")\n"
    }
   ]
  },
  {
   "title": "Encoder Distances (L/R)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"odometry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"posIZ\" or r[\"_field\"] == \"posDR\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Motor Speeds (L/R)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"odometry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"velIZ\" or r[\"_field\"] == \"velDR\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "_OLD_FREERTOS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r._field == \"usage\")\n  |> filter(fn: (r) => r.task != \"TOTAL_CPU0\")\n  |> filter(fn: (r) => r.task != \"TOTAL_CPU1\")\n  |> group(columns: [\"task\"])\n  |> last()\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, task: r.task, display: r.task}))\n  |> keep(columns: [\"_time\", \"_value\", \"task\", \"display\"])\n"
    }
   ]
  },
  {
   "title": "uROS Latency/Jitter (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"esp_diagnostics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\" or r[\"_field\"] == \"jitter\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "FreeRTOS CPU0 Tasks (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r._field == \"usage\")\n  |> filter(fn: (r) => r.task != \"TOTAL_CPU0\")\n  |> filter(fn: (r) => r.task != \"TOTAL_CPU1\")\n  |> filter(fn: (r) =>\n    r.task =~ /cpu0/ or r.task == \"IDLE0\" or r.task == \"main\"\n    or r.task =~ /rtcontrol/ or r.task == \"tiT\"\n    or r.task =~ /emac/ or r.task =~ /esp_timer/\n    or r.task =~ /calib/ or r.task =~ /ipc0/)\n  |> group(columns: [\"task\"])\n  |> last()\n"
    }
   ]
  },
  {
   "title": "FreeRTOS CPU1 Tasks (%)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"local_system\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"cpu_usage\")\n  |> filter(fn: (r) => r._field == \"usage\")\n  |> filter(fn: (r) => r.task != \"TOTAL_CPU0\")\n  |> filter(fn: (r) => r.task != \"TOTAL_CPU1\")\n  |> filter(fn: (r) =>\n    r.task =~ /cpu1/ or r.task == \"IDLE1\"\n    or r.task =~ /comms/ or r.task =~ /monitor/\n    or r.task =~ /uros/ or r.task =~ /mqtt/\n    or r.task =~ /ptp/ or r.task =~ /tel_/\n    or r.task =~ /ipc1/)\n  |> group(columns: [\"task\"])\n  |> last()\n"
    }
   ]
  }
 ]
}