###############################################################################
# AGENT
###############################################################################
[agent]
  ## Intervalo de recolección y envío
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"

  ## Identidad del host en InfluxDB
  hostname = "${HOSTNAME}"
  omit_hostname = false

  ## Control de buffers
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  round_interval = true


###############################################################################
# INPUTS — SISTEMA
###############################################################################

## CPU
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

## Temperatura CPU
[[inputs.exec]]
  commands = ["/etc/telegraf/scripts/cpu_temp.sh"]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  data_format = "value"
  data_type = "float"
  name_override = "cpu_temp"


## Memoria
[[inputs.mem]]

## Disco (uso de filesystem)
[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = [
    "tmpfs",
    "devtmpfs",
    "devfs",
    "iso9660",
    "overlay",
    "aufs",
    "squashfs"
  ]

## I/O de disco
[[inputs.diskio]]
  devices = ["sda", "sdb", "nvme0n1"]
  skip_serial_number = true

## Red Ethernet (Cable)
[[inputs.net]]
  interfaces = ["eth*", "en*"]
  ignore_protocol_stats = false

## Red Inalámbrica (Wi-Fi)
[[inputs.net]]
  interfaces = ["wlan*", "wl*"]
  ignore_protocol_stats = false

## Información general del sistema
[[inputs.system]]


###############################################################################
# INPUTS — MQTT
###############################################################################

[[inputs.mqtt_consumer]]
  # Forzamos 127.0.0.1 dado que 'network_mode: host' ignora a 'mosquitto'
  servers = ["mqtt://127.0.0.1:1883"]
  topics = [
    "robot/telemetry/#",
    "robot/telemetry/follow_line",
    "robot/logs/#",
    "robot/events"
  ]
  qos = 0
  connection_timeout = "30s"
  data_format = "influx"


###############################################################################
# OUTPUTS — INFLUXDB 2.7
###############################################################################

[[outputs.influxdb_v2]]
  ## Endpoint InfluxDB 2.7
  urls = ["http://${INFLUXDB_HOST}:8086"]

  ## Autenticación
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
