###############################################################################
# AGENT
###############################################################################
[agent]
  ## Intervalo de recolección y envío
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"

  ## Identidad del host en InfluxDB
  hostname = "${HOSTNAME}"
  omit_hostname = false

  ## Control de buffers
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  round_interval = true


###############################################################################
# INPUTS — SISTEMA
###############################################################################

## CPU
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

## Memoria
[[inputs.mem]]

## Disco (uso de filesystem)
[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = [
    "tmpfs",
    "devtmpfs",
    "devfs",
    "iso9660",
    "overlay",
    "aufs",
    "squashfs"
  ]

## I/O de disco
[[inputs.diskio]]
  devices = ["sda", "sdb", "nvme0n1"]
  skip_serial_number = true

## Red
[[inputs.net]]
  interfaces = ["eth*", "en*"]
  ignore_protocol_stats = false

## Información general del sistema
[[inputs.system]]


###############################################################################
# INPUTS — MQTT
###############################################################################

[[inputs.mqtt_consumer]]
  servers = ["mqtt://mosquitto:1883"]
  topics = ["robot/performance"]
  qos = 0
  connection_timeout = "30s"
  data_format = "json"

  json_query = ""             # Recorrer array automáticamente
  tag_keys = ["task","core"]  # Extrae estos como tags
  json_string_fields = []     # opcional


###############################################################################
# OUTPUTS — INFLUXDB 3
###############################################################################

[[outputs.influxdb_v2]]
  ## Endpoint InfluxDB 3
  urls = ["http://${INFLUXDB_HOST}:8181"]

  ## Autenticación
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
