apiVersion: 1

datasources:
  - name: InfluxDB_SQL
    type: influxdb
    access: proxy
    url: http://${INFLUXDB_HOST}:${INFLUXDB_HTTP_PORT}
    isDefault: true
    editable: true
    jsonData:
      version: SQL
      dbName: ${INFLUXDB_BUCKET}
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
