apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influx-db:8181
    database: ""
    isDefault: true
    editable: true
    jsonData:
      version: 2
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true
      sqlMode: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
