#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct line_follower_ctrl_context_t* line_follower_ctrl_handle_t;

/**
 * @brief Configuration structure for the Line Follower Controller.
 */
typedef struct {
    float kp;             // Proportional gain
    float ki;             // Integral gain
    float kd;             // Derivative gain
    float base_speed;     // Base straight-line speed
    float max_speed;      // Maximum allowed speed for any motor
    float camera_weight;  // Multiplier for the camera curvature feed-forward
} line_follower_config_t;

/**
 * @brief Input sensory data for the controller.
 */
typedef struct {
    float line_position;    // Evaluated line position (e.g., -1.0 left to 1.0 right)
    bool line_detected;     // True if the line is currently seen by any sensor
    float camera_curvature; // External camera curvature estimate (-1.0 left curve, 1.0 right curve)
} line_follower_input_t;

/**
 * @brief Output speeds generated by the controller.
 */
typedef struct {
    float left_motor_speed;  // Commanded left motor speed
    float right_motor_speed; // Commanded right motor speed
} line_follower_output_t;

/**
 * @brief Creates a new line follower controller instance.
 * 
 * @param config Pointer to the configuration struct.
 * @param out_handle Pointer to store the created handle.
 * @return esp_err_t ESP_OK on success.
 */
esp_err_t line_follower_ctrl_create(const line_follower_config_t* config, line_follower_ctrl_handle_t* out_handle);

/**
 * @brief Destroys the line follower controller instance.
 */
esp_err_t line_follower_ctrl_destroy(line_follower_ctrl_handle_t handle);

/**
 * @brief Updates the controller state and calculates the next motor speeds.
 * 
 * Includes logic for:
 * - PID tracking based on line sensor error.
 * - Feed-forward tracking based on external camera curvature.
 * - Intersection and "lost line" heuristics (going straight in diamonds, spinning when lost).
 * 
 * @param handle Controller handle.
 * @param input Sensor inputs.
 * @param out_output Calculated motor speeds.
 * @param delta_time_s Time elapsed since last update in seconds.
 * @return esp_err_t ESP_OK on success.
 */
esp_err_t line_follower_ctrl_update(line_follower_ctrl_handle_t handle, 
                                    const line_follower_input_t* input, 
                                    line_follower_output_t* out_output,
                                    float delta_time_s);

/**
 * @brief Updates the PID parameters during runtime.
 */
esp_err_t line_follower_ctrl_set_pid(line_follower_ctrl_handle_t handle, float kp, float ki, float kd);

/**
 * @brief Updates the camera feed-forward weight during runtime.
 */
esp_err_t line_follower_ctrl_set_camera_weight(line_follower_ctrl_handle_t handle, float weight);

#ifdef __cplusplus
}
#endif
