services:
  vision:
    build: ./01-vision
    container_name: vision_node
    devices:
      - "/dev/video0:/dev/video0"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ROS_DOMAIN_ID=0
    volumes:
      - ./01-vision/src:/root/vision_node
