services:
  # ===============================
  # VISION (comentado)
  # ===============================
  # vision:
  #   build: ./01-vision
  #   container_name: vision_node
  #   devices:
  #     - "/dev/video0:/dev/video0"
  #   network_mode: "host"
  #   restart: unless-stopped
  #   environment:
  #     - ROS_DOMAIN_ID=13
  #   volumes:
  #     - ./01-vision/src:/root/vision_node

  # ===============================
  # NAVIGATION (comentado)
  # ===============================
  # navigation:
  #   build: ./02-navigation
  #   container_name: navigation_node
  #   network_mode: host
  #   restart: unless-stopped
  #   volumes:
  #     - ./02-navigation/src:/root/navigation_node
  #   environment:
  #     - ROS_DOMAIN_ID=13

  message-broker:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./06-mqtt-broker/mosquitto:/mosquitto/config:ro

  # ===============================
  # INFLUXDB 3 CORE
  # ===============================
  influx-db:
    image: influxdb:3-core
    container_name: influxdb3-core
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUXDB_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    volumes:
      - influxdb-data:/var/lib/influxdb3
    healthcheck:
      test: ["CMD-SHELL", "curl -f -H 'Authorization: Bearer ${INFLUXDB_TOKEN}' http://localhost:8181/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 6
    restart: unless-stopped

  # ===============================
  # TELEGRAF
  # ===============================
  telegraf:
    image: telegraf
    container_name: telegraf
    hostname: telegraf
    restart: unless-stopped
    depends_on:
      influx-db:
        condition: service_healthy
    environment:
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - TELEGRAF_COLLECTION_INTERVAL=${TELEGRAF_COLLECTION_INTERVAL}
      - HOSTNAME=telegraf
    volumes:
      - ./05-telemetry/telegraf:/etc/telegraf

  # ===============================
  # GRAFANA
  # ===============================
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - influx-db

volumes:
  influxdb-data:
  grafana-data:
