#ifndef STUB_SERIALIZATION_SUPPORT_H
#define STUB_SERIALIZATION_SUPPORT_H
typedef struct rosidl_dynamic_typesupport_serialization_support_impl_s { void *dummy; } rosidl_dynamic_typesupport_serialization_support_impl_t;
#endif
